#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "커밋 메시지가 잘못되었습니다.| 예시) feat: 커밋하기" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,80}$"; then
    echo "커밋 메시지가 너무 깁니다." >&2
    exit 1
fi